name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Installing dependencies
        run: npm install
      - name: Build
        run: npm run prepack
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    name: Download dist and release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Installing dependencies
        run: npm install
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Display dirs
        run: ls -R
      - name: Release
        id: release-plugin
        uses: JS-DevTools/npm-publish@v3
        with:
          token: "${{ secrets.NPM_TOKEN }}"
          access: public
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - uses: actions/checkout@v4
        if: ${{ steps.release-plugin.conclusion == 'success'  }}
        with:
          ref: 'prod-qa-pipeline'
      - uses: EndBug/add-and-commit@v9
        if: ${{ steps.release-plugin.conclusion == 'success' }}
        with:
          message: "Released version ${{ steps.package-version.outputs.current-version }}"
          push: true
      - name: github-release
        id: github-release
        env:
          GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }}
          VERSION: ${{ steps.release-plugin.outputs.version }}
        run: gh release create v"$VERSION" --title "Release $VERSION" --generate-notes